Repository kubermatic/kubelb, pull requests merged in 2024-09, with the labels that each got.

#62 Fix multiple load balancers in one tenant
  internal/envoy/resource.go
Labels: kind/bug, approved, ok-to-test, size/S, lgtm, dco-signoff: yes, release-note

#63 Minor improvements for envoy snapshot mapper
  internal/envoy/resource.go
Labels: kind/bug, approved, size/XS, lgtm, dco-signoff: yes, release-note-none

#65 use upstream kube-rbac-proxy from quay.io
  charts/kubelb-ccm/templates/deployment.yaml
  charts/kubelb-manager/templates/deployment.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: approved, size/XS, kind/chore, lgtm, dco-signoff: yes, release-note

#69 Handle possible nil map assignment
  internal/controllers/kubelb/loadbalancer_controller.go
Labels: approved, size/XS, lgtm, dco-signoff: yes, release-note-none
